# Build file for a very basic Nameshed-HSM-Relay container
# config and files to run Nameshed-HSM-Relay must be supplied through volumes
# docker build -t nameshed-hsm-relay-stiab:latest -f dockerfiles/Dockerfile.nameshed-hsm-relay . &&  docker system prune -f && docker buildx prune -f
FROM ubuntu:latest AS build

RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update \
&&  apt-get -y -qq install --no-install-recommends \
    ca-certificates \
    lsb-release \
    wget \
    coreutils \
    curl \
    git-core \
    vim \
    dnsutils \
    iproute2 \
    build-essential \
    pkg-config \
    libssl-dev
RUN apt-get upgrade -y
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && find /var/log -type f -delete
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
ENV PATH="/root/.cargo/bin:$PATH"
RUN echo $PATH
WORKDIR /tmp
RUN git clone --single-branch --branch main https://github.com/NLnetLabs/nameshed-hsm-relay nameshed-hsm-relay
RUN git clone --single-branch --branch next https://github.com/ximon18/keyls keyls
WORKDIR /tmp/nameshed-hsm-relay
RUN git pull \
&&  cargo build --release
WORKDIR /tmp/keyls
RUN git pull \
&&  cargo build --release

FROM ubuntu:latest AS final
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update \
&&  apt-get -y -qq install --no-install-recommends \
    ca-certificates \
    lsb-release \
    wget \
    coreutils \
    curl \
    git-core \
    vim \
    dnsutils \
    iproute2 \
    softhsm2
RUN apt-get upgrade -y
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && find /var/log -type f -delete
RUN useradd --system --home-dir /nameshed --create-home nameshed
RUN softhsm2-util --init-token --label Nameshed --pin 1234 --so-pin 1234 --free
RUN mkdir -p /nameshed/bin
# RUN mkdir -p /nameshed/etc
COPY --from=build /tmp/nameshed-hsm-relay/target/release/nameshed-hsm-relay /nameshed/bin/
COPY --from=build /tmp/keyls/target/release/keyls /nameshed/bin/
COPY --chmod=755 entrypoints/entrypoint_nameshed_hsm_relay.sh /entrypoint.sh
RUN chown -R nameshed:nameshed /nameshed
ENTRYPOINT ["/entrypoint.sh"]
